# Generated by Django 4.1.1 on 2022-10-20 04:11

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('LegacySite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='data',
            field=django_cryptography.fields.encrypt(models.BinaryField(unique=True)),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=97)),
        ),
    ]
